language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 7.0
  - hhvm

branches:
  only:
    - master
    - develop
    - /^feature\/\d+$/

matrix:
  include:
    - php: 5.6
      env:
        - PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
        - COVERAGE=true
    - php: 5.5
      env: SYMFONY_VERSION='2.3.*'
    - php: 5.5
      env:
        - SYMFONY_VERSION='2.4.*'
    - php: 5.5
      env:
        - SYMFONY_VERSION='2.5.*'
    - php: 5.5
      env:
        - SYMFONY_VERSION='2.6.*'
    - php: 5.5
      env:
        - SYMFONY_VERSION='2.7.*@dev'

before_script:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - composer install

script:
  - phpunit ${PHPUNIT_FLAGS}

after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

after_failure:
  - cat /tmp/fos-http-cache-bundle/logs/test.log